openapi: 3.0.0
info:
  title: Employee Management System API
  description: API for managing employees in the system.
  version: "1.0.0"
paths:
  /api/employees:
    post:
      summary: Add a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    get:
      summary: Get an employee by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The employee ID
      responses:
        '200':
          description: Employee details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /api/employees/{id}:
    put:
      summary: Update an employee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The employee ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    delete:
      summary: Delete an employee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The employee ID
      responses:
        '200':
          description: Employee deleted successfully
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        department:
          type: string
        salary:
          type: number
          format: float