spring:
 datasource:
  url: jdbc:mysql://localhost:3306/students
  username: root
  password: welcome123
 jpa:
  hibernate:
   ddl-auto:update
 properties:
  hibernate:
   dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: eduelevate
server:
 port: 9090


